# Travis CI build file for SwiftKueryMySQL.
# SwiftKueryMySQL runs on OS X and Linux (Ubuntu).
# See the following URLs for further details on Travis CI
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/multi-os/

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

services:
  - mysql

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_VERSION=3.0.2
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3
      sudo: required

script:
  - ./build.sh
