# Travis CI build file for SwiftKueryMySQL.
# SwiftKueryMySQL runs on OS X and Linux (Ubuntu).
# See the following URLs for further details on Travis CI
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/multi-os/

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

services:
  - mysql

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_VERSION=3.0.2
    - os: osx
      osx_image: xcode8.3
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git
  - test -n "$SWIFT_VERSION" && echo "$SWIFT_VERSION" > .swift-version || echo "SWIFT_VERSION not set, using $(cat .swift-version)"
  - mysql -e "CREATE USER 'swift'@'localhost' IDENTIFIED BY 'kuery';"
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;"
  - mysql -e "GRANT ALL ON test.* TO 'swift'@'localhost';"

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
